{"name": "test02_mis_search", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <scripts.test02_mis.TestMis object at 0x00000209E9D22F60>\n\n    def test02_mis_search(self):\n        # 1.调用查询文章接口\n        r = self.mis.api_mis_search()\n        try:\n            # 2.断言\n>           Tool.common_assert(r, status_code=200) # 状态码为int型200 不加引号\n\nscripts\\test02_mis.py:40: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ncls = <class 'tool.tool.Tool'>, response = <Response [403]>, status_code = 200\n\n    @classmethod\n    def common_assert(cls, response, status_code=201):\n        log.info(\"正在调用公共断言方法！\")\n        # 断言状态码\n>       assert status_code == response.status_code\nE       AssertionError\n\ntool\\tool.py:21: AssertionError"}, "attachments": [{"name": "log", "source": "5386ff87-cf24-4b1a-b7eb-03036589b107-attachment.txt", "type": "text/plain"}], "start": 1628853508844, "stop": 1628853508925, "uuid": "3f6086ed-8afc-4353-851e-300b8cafc95f", "historyId": "3f73d307b052a1555ac345fb66f890ec", "testCaseId": "717bcced00d6f137cd9d7d4949eeb939", "fullName": "scripts.test02_mis.TestMis#test02_mis_search", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test02_mis"}, {"name": "subSuite", "value": "TestMis"}, {"name": "host", "value": "DESKTOP-3AQ9FK9"}, {"name": "thread", "value": "2564-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test02_mis"}]}