{"name": "test03_mis_audit", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <scripts.test02_mis.TestMis object at 0x00000201DD567C50>\n\n    def test03_mis_audit(self):\n        # 1.调用审核文章方法\n        r = self.mis.api_mis_audit()\n        try:\n            # 2.断言\n>           Tool.common_assert(r)\n\nscripts\\test02_mis.py:53: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ncls = <class 'tool.tool.Tool'>, response = <Response [403]>, status_code = 201\n\n    @classmethod\n    def common_assert(cls, response, status_code=201):\n        log.info(\"正在调用公共断言方法！\")\n        # 断言状态码\n>       assert status_code == response.status_code\nE       AssertionError\n\ntool\\tool.py:21: AssertionError"}, "attachments": [{"name": "log", "source": "51c8c6f1-9e5d-4b3d-8a41-19da96478ce7-attachment.txt", "type": "text/plain"}], "start": 1628842144437, "stop": 1628842144555, "uuid": "25a5166a-cb62-4c24-bea0-e9bbf274af6b", "historyId": "b465eea778f8ece01716f4527f84b689", "testCaseId": "90ff882230c9f80dbc7a2baf9bff7e41", "fullName": "scripts.test02_mis.TestMis#test03_mis_audit", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test02_mis"}, {"name": "subSuite", "value": "TestMis"}, {"name": "host", "value": "DESKTOP-3AQ9FK9"}, {"name": "thread", "value": "11536-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test02_mis"}]}